@echo off
echo Setting up and starting the Backend Server...
cd backend
if not exist "venv" (
    echo Creating virtual environment...
    python -m venv venv
)
call venv\Scripts\activate.bat
echo Installing requirements...
pip install -r requirements.txt
echo Generating sample Excel file for testing...
python ..\create_sample.py
echo Starting FastAPI server...
uvicorn main:app --reload --host 0.0.0.0 --port 8000
pause
